/-
Copyright (c) 2026 The NeSyCat Project (Daniel Romero Schellhorn). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Romero Schellhorn
-/
import Mathlib
import NeSyCat.BlueprintAttr
import NeSyCat.DomainLayer.DomainLayer
import NeSyCat.GrammaticalLayer.Context

/-!
# Grammatical signature

Blueprint item `def:grammatical-signature` (`blueprint/src/content.tex`,
§"Grammatical layer", `NeSyCat Theory v2`, `new.tex` 1--396): a
grammatical signature `Σ_δ` is generated over a domain signature `Σ_γ`
and a logical signature `Σ_β` by a six-rule context-free grammar of
terms `Ξ` and formulas `Φ`, the last rule (substitution) generating
formulas *explicitly* rather than only as a meta-operation.

**Codes + interpretation, extrinsic typing.** `Tm`/`Fm` below are the
raw, *untyped* syntax generated by the grammar (a `Type`, never a
`Prop`): every one of the six rules becomes a constructor, with no
arity/typing side condition baked into the constructor's own type. All
well-formedness (arity match against `sigG.fdom`/`sigG.rari`/`sigB.connArity`,
`x ∈ [φ]` for the substitution rule, and context distinctness) is
carried instead by the extrinsic Prop predicates `Tm.WellFormed`/
`Fm.WellFormed` below, decided separately from the syntax itself, per
the library's typing doctrine (raw syntax inductives + typing as `Prop`
side conditions).

**`inn`/`out`/`on`, structural.** `Tm.inn`/`Fm.on` compute a term's or
formula's free variables by structural recursion over the syntax (no
well-founded measure, matching the structural-recursion discipline the
later Kleisli interpretation needs). The document types
`inn, out : Ξ → 𝓛(Var)` uniformly, but only ever *consumes* `out` on a
variable term (where `inn(ξ) = out(ξ)` is the one stated law) — its own
typing table for the Kleisli interpretation (`⟦f(ξ⃗)⟧ : 𝓘(inn(ξ⃗)) → 𝓜
𝓘(cod(f))`) reads the codomain of a functional term off `sigG.fcod f`
directly, never off a second, independently-computed `out(f(ξ⃗))`
formula — the document gives no rule for inventing fresh output-variable
names for a functional term's outputs. `Tm.out` is accordingly defined
equal to `Tm.inn`, honoring the one stated law exactly and disclosing
that no other clause distinguishes it; a future revision that pins down
fresh-name generation for multi-output terms would revisit this.
-/

namespace NeSyCat

mutual

/-- Companion of `def:grammatical-signature`: the raw, untyped syntax
of terms `Ξ`, generated over a domain signature `sigG` and a logical
signature `sigB` by the grammar's first two rules — `ξ ::= x`
(`x ∈ Var`, a variable term) and `ξ ::= f(ξ⃗)` (`f ∈ Fun`, a functional
term). Together with `Fm` (`Φ`), bundled by the cited principal
declaration `GramSignature` below. -/
@[blueprint_internal] -- companion of def:grammatical-signature: one
-- half of the bundled principal `GramSignature`, `Ξ`
inductive Tm (sigG : DomSignature) (sigB : LogSignature) : Type where
  /-- `ξ ::= x`, `x ∈ Var`: a variable term. -/
  | var (x : sigG.Var) : Tm sigG sigB
  /-- `ξ ::= f(ξ⃗)`, `f ∈ Fun`: a functional term. -/
  | app (f : sigG.Fun) (args : List (Tm sigG sigB)) : Tm sigG sigB

/-- Companion of `def:grammatical-signature`: the raw, untyped syntax
of formulas `Φ`, generated over a domain signature `sigG` and a logical
signature `sigB` by the grammar's remaining four rules — `φ ::= R(ξ⃗)`
(`R ∈ Rel`, an atomic formula), `φ ::= *(φ⃗)` (`* ∈ Conn`, a compound
formula), `φ ::= Qx⃗(φ)` (`Q ∈ Quan`, a quantified formula), and
`φ ::= φ[x := ξ]` (`x` a free variable of `φ`, `ξ` any term, a
substituted formula) — the last rule generating formulas *explicitly*,
as its own constructor, rather than only as a meta-level operation on
already-generated formulas. Together with `Tm` (`Ξ`), bundled by the
cited principal declaration `GramSignature` below. -/
@[blueprint_internal] -- companion of def:grammatical-signature: the
-- other half of the bundled principal `GramSignature`, `Φ`
inductive Fm (sigG : DomSignature) (sigB : LogSignature) : Type where
  /-- `φ ::= R(ξ⃗)`, `R ∈ Rel`: an atomic formula. -/
  | rel (R : sigG.Rel) (args : List (Tm sigG sigB)) : Fm sigG sigB
  /-- `φ ::= *(φ⃗)`, `* ∈ Conn`: a compound formula. -/
  | conn (c : sigB.Conn) (args : List (Fm sigG sigB)) : Fm sigG sigB
  /-- `φ ::= Qx⃗(φ)`, `Q ∈ Quan`: a quantified formula, binding the list
  of variables `x⃗`. -/
  | quant (Q : sigB.Quan) (xs : List sigG.Var) (body : Fm sigG sigB) : Fm sigG sigB
  /-- `φ ::= φ[x := ξ]`, `x` a free variable of `φ` and `ξ` any term: a
  substituted formula, generated *explicitly* by the grammar. -/
  | subst (body : Fm sigG sigB) (x : sigG.Var) (t : Tm sigG sigB) : Fm sigG sigB

end

/-- Blueprint `def:grammatical-signature` (Grammatical signature),
principal declaration: the grammatical signature `Σδ`, given by the set
of terms `Ξ` (`Tm`) and the set of formulas `Φ` (`Fm`) the six-rule
grammar generates — bundled here as the pair of Types itself (`Ξ, Φ`),
matching the environment's own "given by a set of terms Ξ … and a set
of formulas Φ" phrasing. Kept a plain `def` (not `structure`) since
`Σδ` names no further data beyond `Ξ`/`Φ` themselves — `inn`/`out`/`on`
below are structural functions on `Tm`/`Fm`, not extra signature
fields. -/
def GramSignature (sigG : DomSignature) (sigB : LogSignature) : Type × Type :=
  (Tm sigG sigB, Fm sigG sigB)

variable {sigG : DomSignature} {sigB : LogSignature}

/-- Companion of `def:grammatical-signature`: `inn(ξ)`, a term's context
of free variables, computed by structural recursion — `[x]` for a
variable term, the concatenation of the argument terms' own `inn`s for a
functional term. Not deduplicated (context distinctness is an extrinsic
`Tm.WellFormed`/`Fm.WellFormed` side condition, per this file's typing
doctrine, not baked into `inn`'s return type). -/
@[blueprint_internal] -- companion structural def, `inn : Ξ → 𝓛(Var)`
def Tm.inn : Tm sigG sigB → List sigG.Var
  | .var x => [x]
  | .app _ args => (args.map Tm.inn).flatten

/-- Companion of `def:grammatical-signature`: `out(ξ)`, a term's context
of typed outputs. Defined equal to `inn` — see this file's module doc
for why the document gives no separate formula for `out` on a functional
term (`inn(ξ) = out(ξ)` is the one law it states, for variable terms,
and its own Kleisli-interpretation typing table reads a functional
term's codomain off `sigG.fcod f` directly, never off a second
independently-computed `out`). -/
@[blueprint_internal] -- companion structural def, `out : Ξ → 𝓛(Var)`,
-- disclosed equal to `inn` (module doc)
def Tm.out : Tm sigG sigB → List sigG.Var := Tm.inn

/-- Companion of `def:grammatical-signature`: `on(φ) = [φ]`, a formula's
canonical context of free variables, computed by structural recursion —
the union (as list concatenation) of the arguments' free variables for
an atomic or compound formula, the bound variables `x⃗` removed for a
quantified formula, and `x` removed with `ξ`'s own free variables `inn t`
appended for a substituted formula (matching the document's later
`[φ[x:=ξ]] = [φ]_{[x]↦inn(ξ)}` positional-replacement reading at the
unordered, set-of-occurrences level). Not deduplicated, for the same
reason as `Tm.inn`. -/
@[blueprint_internal] -- companion structural def, `on : Φ → 𝓛(Var)`
def Fm.on [DecidableEq sigG.Var] : Fm sigG sigB → List sigG.Var
  | .rel _ args => (args.map Tm.inn).flatten
  | .conn _ args => (args.map Fm.on).flatten
  | .quant _ xs body => body.on.filter (· ∉ xs)
  | .subst body x t => (body.on.filter (· ≠ x)) ++ t.inn

/-- Companion of `def:grammatical-signature`'s typing doctrine: a term
is well-formed when every functional-term node's argument list matches
its function symbol's declared domain arity (`sigG.fdom f`), recursively
on the arguments. -/
@[blueprint_internal] -- companion extrinsic WF predicate for `Tm`
def Tm.WellFormed : Tm sigG sigB → Prop
  | .var _ => True
  | .app f args => (sigG.fdom f).length = args.length ∧ ∀ a ∈ args, a.WellFormed

/-- Companion of `def:grammatical-signature`'s typing doctrine: a
formula is well-formed when every relation/connective node's argument
list matches its symbol's declared arity (`sigG.rari R`/`sigB.connArity c`),
every quantified formula binds a *distinct* list of variables actually
free in its body (`x⃗ ⊆ [φ]`, `x⃗.Nodup`), every substituted formula
substitutes for a variable actually free in its body (`x ∈ [φ]`), and
every argument/subterm/body is itself well-formed — the pin's three
named conditions (arity match, `x ∈ [φ]`, context distinctness), decided
extrinsically from the untyped grammar of `Tm`/`Fm`. -/
@[blueprint_internal] -- companion extrinsic WF predicate for `Fm`
def Fm.WellFormed [DecidableEq sigG.Var] : Fm sigG sigB → Prop
  | .rel R args => (sigG.rari R).length = args.length ∧ ∀ a ∈ args, a.WellFormed
  | .conn c args => sigB.connArity c = args.length ∧ ∀ a ∈ args, a.WellFormed
  | .quant _ xs body => xs.Nodup ∧ (∀ x ∈ xs, x ∈ body.on) ∧ body.WellFormed
  | .subst body x t => x ∈ body.on ∧ body.WellFormed ∧ t.WellFormed

-- (completeness census, same pattern as `MonSym`/`CatSignature` in
-- `NeSyCat/CategoricalLayer/Signatures/Signatures.lean`: equation-lemma
-- and recursor byproducts of `Tm`/`Fm`'s mutual inductive and their
-- structural companions, with no attribute site of their own, tagged
-- post-hoc -- not blueprint-cited, plumbing of `GramSignature`/`inn`/
-- `on`/`WellFormed`)
attribute [blueprint_internal] Tm.brecOn.go Tm.brecOn.eq Tm.brecOn_1.go Tm.brecOn_1.eq
  Tm.brecOn_2.go Tm.brecOn_2.eq Fm.brecOn.go Fm.brecOn.eq Tm.ctorElimType Fm.ctorElimType
  Tm.inn.eq_def Fm.on.eq_def Tm.WellFormed.eq_def Fm.WellFormed.eq_def

end NeSyCat
