/-
Copyright (c) 2026 The NeSyCat Project (Daniel Romero Schellhorn). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Romero Schellhorn
-/
import Mathlib
import NeSyCat.BlueprintAttr
import NeSyCat.DomainLayer.DomainLayer
import NeSyCat.GrammaticalLayer.Context

/-!
# Grammatical signature

Blueprint item `def:grammatical-signature` (`blueprint/src/content.tex`,
§"Grammatical layer", `NeSyCat Theory v2`, `new.tex` 1--396): a
grammatical signature `Σ_δ` is generated over a domain signature `Σ_γ`
and a logical signature `Σ_β` by a six-rule context-free grammar of
terms `Ξ` and formulas `Φ`, the last rule (substitution) generating
formulas *explicitly* rather than only as a meta-operation.

**Codes + interpretation, extrinsic typing.** `Tm`/`Fm` below are the
raw, *untyped* syntax generated by the grammar (a `Type`, never a
`Prop`): every one of the six rules becomes a constructor, with no
arity/typing side condition baked into the constructor's own type. All
well-formedness (arity match against `sigG.fdom`/`sigG.rari`/`sigB.connArity`,
`x ∈ [φ]` for the substitution rule, and context distinctness) is
carried instead by the extrinsic Prop predicates `Tm.WellFormed`/
`Fm.WellFormed` below, decided separately from the syntax itself, per
the library's typing doctrine (raw syntax inductives + typing as `Prop`
side conditions).

**`inn`/`out`/`on`, structural.** `Tm.inn`/`Fm.on` compute a term's or
formula's free variables by structural recursion over the syntax (no
well-founded measure, matching the structural-recursion discipline the
later Kleisli interpretation needs). The document types
`inn, out : Ξ → 𝓛(Var)` uniformly, but only ever *consumes* `out` on a
variable term (where `inn(ξ) = out(ξ)` is the one stated law) — its own
typing table for the Kleisli interpretation (`⟦f(ξ⃗)⟧ : 𝓘(inn(ξ⃗)) → 𝓜
𝓘(cod(f))`) reads the codomain of a functional term off `sigG.fcod f`
directly, never off a second, independently-computed `out(f(ξ⃗))`
formula — the document gives no rule for inventing fresh output-variable
names for a functional term's outputs. `Tm.out` is accordingly defined
equal to `Tm.inn`, honoring the one stated law exactly and disclosing
that no other clause distinguishes it; a future revision that pins down
fresh-name generation for multi-output terms would revisit this.
-/

namespace NeSyCat

mutual

/-- Companion of `def:grammatical-signature`: the raw, untyped syntax
of terms `Ξ`, generated over a domain signature `sigG` and a logical
signature `sigB` by the grammar's first two rules — `ξ ::= x`
(`x ∈ Var`, a variable term) and `ξ ::= f(ξ⃗)` (`f ∈ Fun`, a functional
term). Together with `Fm` (`Φ`), bundled by the cited principal
declaration `GramSignature` below. -/
@[blueprint_internal] -- companion of def:grammatical-signature: one
-- half of the bundled principal `GramSignature`, `Ξ`
inductive Tm (sigG : DomSignature) (sigB : LogSignature) : Type where
  /-- `ξ ::= x`, `x ∈ Var`: a variable term. -/
  | var (x : sigG.Var) : Tm sigG sigB
  /-- `ξ ::= f(ξ⃗)`, `f ∈ Fun`: a functional term. -/
  | app (f : sigG.Fun) (args : List (Tm sigG sigB)) : Tm sigG sigB

/-- Companion of `def:grammatical-signature`: the raw, untyped syntax
of formulas `Φ`, generated over a domain signature `sigG` and a logical
signature `sigB` by the grammar's remaining four rules — `φ ::= R(ξ⃗)`
(`R ∈ Rel`, an atomic formula), `φ ::= *(φ⃗)` (`* ∈ Conn`, a compound
formula), `φ ::= Qx⃗(φ)` (`Q ∈ Quan`, a quantified formula), and
`φ ::= φ[x := ξ]` (`x` a free variable of `φ`, `ξ` any term, a
substituted formula) — the last rule generating formulas *explicitly*,
as its own constructor, rather than only as a meta-level operation on
already-generated formulas. Together with `Tm` (`Ξ`), bundled by the
cited principal declaration `GramSignature` below. -/
@[blueprint_internal] -- companion of def:grammatical-signature: the
-- other half of the bundled principal `GramSignature`, `Φ`
inductive Fm (sigG : DomSignature) (sigB : LogSignature) : Type where
  /-- `φ ::= R(ξ⃗)`, `R ∈ Rel`: an atomic formula. -/
  | rel (R : sigG.Rel) (args : List (Tm sigG sigB)) : Fm sigG sigB
  /-- `φ ::= *(φ⃗)`, `* ∈ Conn`: a compound formula. -/
  | conn (c : sigB.Conn) (args : List (Fm sigG sigB)) : Fm sigG sigB
  /-- `φ ::= Qx⃗(φ)`, `Q ∈ Quan`: a quantified formula, binding the list
  of variables `x⃗`. -/
  | quant (Q : sigB.Quan) (xs : List sigG.Var) (body : Fm sigG sigB) : Fm sigG sigB
  /-- `φ ::= φ[x := ξ]`, `x` a free variable of `φ` and `ξ` any term: a
  substituted formula, generated *explicitly* by the grammar. -/
  | subst (body : Fm sigG sigB) (x : sigG.Var) (t : Tm sigG sigB) : Fm sigG sigB

end

/-- Blueprint `def:grammatical-signature` (Grammatical signature),
principal declaration: the grammatical signature `Σδ`, given by the set
of terms `Ξ` (`Tm`) and the set of formulas `Φ` (`Fm`) the six-rule
grammar generates — bundled here as the pair of Types itself (`Ξ, Φ`),
matching the environment's own "given by a set of terms Ξ … and a set
of formulas Φ" phrasing. Kept a plain `def` (not `structure`) since
`Σδ` names no further data beyond `Ξ`/`Φ` themselves — `inn`/`out`/`on`
below are structural functions on `Tm`/`Fm`, not extra signature
fields. -/
def GramSignature (sigG : DomSignature) (sigB : LogSignature) : Type × Type :=
  (Tm sigG sigB, Fm sigG sigB)

variable {sigG : DomSignature} {sigB : LogSignature}

/-- Companion of `def:grammatical-signature`: `inn(ξ)`, a term's context
of free variables, computed by structural recursion — `[x]` for a
variable term, the concatenation of the argument terms' own `inn`s for a
functional term. Not deduplicated (context distinctness is an extrinsic
`Tm.WellFormed`/`Fm.WellFormed` side condition, per this file's typing
doctrine, not baked into `inn`'s return type). -/
@[blueprint_internal] -- companion structural def, `inn : Ξ → 𝓛(Var)`
def Tm.inn : Tm sigG sigB → List sigG.Var
  | .var x => [x]
  | .app _ args => (args.map Tm.inn).flatten

/-- Companion of `def:grammatical-signature`: `out(ξ)`, a term's context
of typed outputs. Defined equal to `inn` — see this file's module doc
for why the document gives no separate formula for `out` on a functional
term (`inn(ξ) = out(ξ)` is the one law it states, for variable terms,
and its own Kleisli-interpretation typing table reads a functional
term's codomain off `sigG.fcod f` directly, never off a second
independently-computed `out`). -/
@[blueprint_internal] -- companion structural def, `out : Ξ → 𝓛(Var)`,
-- disclosed equal to `inn` (module doc)
def Tm.out : Tm sigG sigB → List sigG.Var := Tm.inn

/-- Companion of `def:grammatical-signature`/`def:context`'s CONTEXT
FIDELITY repair (C3-B4-FIX item 1): `[φ]` is a **context** (a list of
*distinct* variables, `def:context`), so `on` must deduplicate — an
order-preserving, first-occurrence dedup, matching the document's own
left-to-right ordered-context reading (`firstDedup [1,2,1,3,2] =
[1,2,3]`, keeping the position of each variable's *first* appearance,
in contrast to Mathlib's own `List.dedup`, which keeps the *last*
occurrence). Structural recursion on the list, threading the head's
survival through a `filter` on the recursively-deduplicated tail — the
building block `Fm.on` below composes with `Kleisli.lean`'s `ctxCopy`
companion to route one copy of each surviving variable to every
occurrence the raw (non-deduplicated) argument-list concatenation still
needs. -/
@[blueprint_internal] -- companion of def:grammatical-signature/def:context:
-- the order-preserving first-occurrence dedup `on`'s context fidelity needs
def firstDedup {α : Type*} [DecidableEq α] : List α → List α
  | [] => []
  | x :: xs => x :: (firstDedup xs).filter (fun v => decide (v ≠ x))

/-- Companion of `firstDedup`: the result never drops a variable
present in the original list — feeds `Kleisli.lean`'s `ctxCopy`'s own
membership hypothesis (`∀ x ∈ l, x ∈ firstDedup l`). -/
@[blueprint_internal] -- companion of def:grammatical-signature/def:context:
-- firstDedup retains every element (as a membership witness)
theorem mem_firstDedup {α : Type*} [DecidableEq α] :
    ∀ {l : List α} {y : α}, y ∈ l → y ∈ firstDedup l
  | x :: xs, y, hy => by
    rcases List.mem_cons.mp hy with rfl | hy'
    · exact List.mem_cons_self ..
    · by_cases hxy : y = x
      · subst hxy; exact List.mem_cons_self ..
      · exact List.mem_cons_of_mem _
          (List.mem_filter.mpr ⟨mem_firstDedup hy', by simp [hxy]⟩)

/-- Companion of `firstDedup`: the result is itself a genuine context —
distinct variables, `def:context` — feeding `Kleisli.lean`'s `ctxCopy`'s
own `Nodup` hypothesis. -/
@[blueprint_internal] -- companion of def:grammatical-signature/def:context:
-- firstDedup produces a Nodup list
theorem firstDedup_nodup {α : Type*} [DecidableEq α] :
    ∀ l : List α, (firstDedup l).Nodup
  | [] => List.nodup_nil
  | x :: xs => by
    refine List.Nodup.cons ?_ ((firstDedup_nodup xs).filter _)
    intro hmem
    have := (List.mem_filter.mp hmem).2
    simp at this

/-- Companion of `def:grammatical-signature`: `on(φ) = [φ]`, a formula's
canonical context of free variables, computed by structural recursion —
the order-preserving first-occurrence dedup (`firstDedup`, this file's
module doc, C3-B4-FIX item 1) of the concatenated arguments' free
variables for an atomic or compound formula (`Kleisli.lean`'s `ctxCopy`
routes one copy of each surviving shared variable to every argument
that uses it, matching the document's own $\mathsf{copy}$ description),
the bound variables `x⃗` removed for a quantified formula (already
distinct by the recursive `on`, so a plain `filter` keeps it a context,
no dedup needed here), and — for a substituted formula, C3-B4-FIX item
2 — `x` replaced **positionally**, at its own occurrence in `body.on`
(not appended at the list's end), by `ξ`'s free variables `t.inn`,
matching the document's `[φ]_{[x]↦inn(ξ)}` = `[y₁,…,y_{p-1}] + inn(ξ) +
[y_{p+1},…,y_m]` reading exactly, via `List.takeWhile`/`List.dropWhile`
splitting `body.on` at `x`'s position. -/
@[blueprint_internal] -- companion structural def, `on : Φ → 𝓛(Var)`
def Fm.on [DecidableEq sigG.Var] : Fm sigG sigB → List sigG.Var
  | .rel _ args => firstDedup (args.map Tm.inn).flatten
  | .conn _ args => firstDedup (args.map Fm.on).flatten
  | .quant _ xs body => body.on.filter (· ∉ xs)
  | .subst body x t =>
    body.on.takeWhile (fun v => decide (v ≠ x)) ++
      (t.inn ++ (body.on.dropWhile (fun v => decide (v ≠ x))).tail)

/-- Companion of `Fm.on`'s substitution clause (C3-B4-FIX item 2): the
`takeWhile`/`dropWhile` split at `x`'s position reassembles exactly the
original list, given only that `x` occurs somewhere in it — the
document's own `x ∈ [φ]` side condition and nothing more (C3-B4-FIX
item 4), consumed by `Kleisli.lean`'s `Fm.sem` substitution clause to
identify the reassembled domain object with `ctxObj D body.on`. -/
@[blueprint_internal] -- companion of def:grammatical-signature: the
-- position-split reassembly lemma the subst clause's sem needs
theorem list_split_pre_post {α : Type*} [DecidableEq α] :
    ∀ {l : List α} {x : α}, x ∈ l →
      l.takeWhile (fun v => decide (v ≠ x)) ++
        x :: (l.dropWhile (fun v => decide (v ≠ x))).tail = l
  | y :: l', x, hx => by
    by_cases hxy : y = x
    · subst hxy
      simp [List.takeWhile, List.dropWhile]
    · have hx' : x ∈ l' := (List.mem_cons.mp hx).resolve_left (Ne.symm hxy)
      have hne : decide (y ≠ x) = true := by simpa using hxy
      simp only [List.takeWhile, List.dropWhile, hne, List.cons_append]
      exact congrArg (y :: ·) (list_split_pre_post hx')

/-- Companion of `def:grammatical-signature`'s typing doctrine: a term
is well-formed when every functional-term node's argument list matches
its function symbol's declared domain arity (`sigG.fdom f`), recursively
on the arguments. -/
@[blueprint_internal] -- companion extrinsic WF predicate for `Tm`
def Tm.WellFormed : Tm sigG sigB → Prop
  | .var _ => True
  | .app f args => (sigG.fdom f).length = args.length ∧ ∀ a ∈ args, a.WellFormed

/-- Companion of `def:grammatical-signature`'s typing doctrine: a
formula is well-formed when every relation/connective node's argument
list matches its symbol's declared arity (`sigG.rari R`/`sigB.connArity c`),
every quantified formula binds a *distinct* list of variables actually
free in its body (`x⃗ ⊆ [φ]`, `x⃗.Nodup`), every substituted formula
substitutes for a variable actually free in its body (`x ∈ [φ]`), and
every argument/subterm/body is itself well-formed — the pin's three
named conditions (arity match, `x ∈ [φ]`, context distinctness), decided
extrinsically from the untyped grammar of `Tm`/`Fm`. -/
@[blueprint_internal] -- companion extrinsic WF predicate for `Fm`
def Fm.WellFormed [DecidableEq sigG.Var] : Fm sigG sigB → Prop
  | .rel R args => (sigG.rari R).length = args.length ∧ ∀ a ∈ args, a.WellFormed
  | .conn c args => sigB.connArity c = args.length ∧ ∀ a ∈ args, a.WellFormed
  | .quant _ xs body => xs.Nodup ∧ (∀ x ∈ xs, x ∈ body.on) ∧ body.WellFormed
  | .subst body x t => x ∈ body.on ∧ body.WellFormed ∧ t.WellFormed

-- (completeness census, same pattern as `MonSym`/`CatSignature` in
-- `NeSyCat/CategoricalLayer/Signatures/Signatures.lean`: equation-lemma
-- and recursor byproducts of `Tm`/`Fm`'s mutual inductive and their
-- structural companions, with no attribute site of their own, tagged
-- post-hoc -- not blueprint-cited, plumbing of `GramSignature`/`inn`/
-- `on`/`WellFormed`)
attribute [blueprint_internal] Tm.brecOn.go Tm.brecOn.eq Tm.brecOn_1.go Tm.brecOn_1.eq
  Tm.brecOn_2.go Tm.brecOn_2.eq Fm.brecOn.go Fm.brecOn.eq Tm.ctorElimType Fm.ctorElimType
  Tm.inn.eq_def Fm.on.eq_def Tm.WellFormed.eq_def Fm.WellFormed.eq_def

end NeSyCat
